[package]
name = "Aoc-2022-07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.7.0"
anyhow = "1.0.66"